server:
  port: 8888

# 配置文件加密key
jasypt:
  encryptor:
    password: monkeyzi

spring:
  profiles:
     active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/job_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: guoguo
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: ENC(ly6ALRqFlY9vVwnabWCg+5j/J7PdUuHe)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(ly6ALRqFlY9vVwnabWCg+5j/J7PdUuHe)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
  # Redis
  redis:
    host: 127.0.0.1
    password: ENC(sAxR1yuo9TKgVO4rpYtgEw==)
    database: 0
    port: 6379
    timeout: 5000ms



# 定时任务
quartz:
  # 任务信息存储至数据库
  job-store-type: jdbc
# 文件大小上传配置
servlet:
  multipart:
    max-file-size: 5Mb
    max-request-size: 5Mb
# 忽略鉴权url
ignored:
  urls:
    - /auth/**
    - /user/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**
#mybatis
mybatis:
  type-aliases-package: com.monkeyzi.oauth.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.monkeyzi.oauth.base.mybatis.MyMapper
  not-empty: false
  identity: MYSQL

#oauth2 client配置
monkeyzi:
   security:
      oauth2:
        jwtSigningKey: monkeyzi
        tokenStore: jwt
        clients[0]:
          clientId: monkeyziClientId
          clientSecret: monkeyziClientSecret
          accessTokenValidateSeconds: 7200
          scope: "*"
      brower:
        # 记住我功能 7day
        rememberMeSeconds: 604800
   task:
      corePoolSize: 5
      maxPoolSize: 50
      queueCapacity: 10000
      keepAliveSeconds: 3000
      threadNamePrefix: monkeyzi-task-executor-
   # 高德地图ip获取城市
   gaode:
      key: 7ef566131d3a7c1e8a1c13fd41393fba
   # 全局限流
   rateLimit:
      enable: true
      # 每1秒内
      timeout: 1000
      # 总限制100个请求
      limit: 100
   loginLimit:
      # 限制用户登陆错误次数（次）
      loginTimeLimit: 5
      # 错误超过次数后多少分钟后才能继续登录（分钟）
      loginAfterTime: 10
   im:
       # null代表监听所有的ip
      bindIp: null
      bindPort: 9999
      heartBeatTimeout: 60
      charset: utf-8
      protocolName: monkeyzi-socket