server:
  port: 8888

# 配置文件加密key
jasypt:
  encryptor:
    password: monkeyzi

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # 数据源
  datasource:
    url: jdbc:mysql://59.110.171.71:3306/job_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: guoguo
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    password: ENC(ly6ALRqFlY9vVwnabWCg+5j/J7PdUuHe)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(ly6ALRqFlY9vVwnabWCg+5j/J7PdUuHe)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
# Redis
redis:
  host: 127.0.0.1
  password:
  # 数据库索引 默认0
  database: 0
  port: 6379
  timeout: 3000
# 定时任务
quartz:
  # 任务信息存储至数据库
  job-store-type: jdbc
# 文件大小上传配置
servlet:
  multipart:
    max-file-size: 5Mb
    max-request-size: 5Mb
# 忽略鉴权url
ignored:
  urls:
    - /auth/**
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /test/**

# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.monkeyzi.oauth.entity
  typeEnumsPackage: com.monkeyzi.oauth.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#oauth2 client配置
monkeyzi:
   security:
      oauth2:
        jwtSigningKey: monkeyzi
        tokenStore: jwt
        clients[0]:
          clientId: monkeyziClientId
          clientSecret: monkeyziClientSecret
          accessTokenValidateSeconds: 7200
          scope: "*"